import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slogan>
          <Intro>
            <span className="name">WJY :Ｐ</span>
            <span>- A good boy.</span>
            <span>- A Frontend guy. </span>
            <span>- Love music & guitar.</span>
            <span>- Like coding.</span>
          </Intro>
        </Slogan>
      </main>
    </>
  )
}

const Test = styled.div``;

const Slogan = styled.div`
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Intro = styled.div`
  display: grid;
  gap: 8px;

  .name {
    font-size: 2rem;
    font-weight: bold;
  }
`;