name: Build & Deploy 🤓

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing
        run: |
          echo "Install deps..."
          npm ci

      - name: Build proj  
        run: |
          echo "Next project build..."
          npm run build
        
      - name: Lint checks
        run: |
          echo "Check linting..."
          npm lint
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages